export {default as Home} from './Home'
export {default as About} from './About'
export {default as ServicesPage} from './ServicesPage'
export {default as SkinCare} from './SkinCare/SkinCare'
export {default as Contact} from './Contact'
export {default as SkinCareDetails} from './SkinCare/SkinCareDetails'